import random
import datetime
import math

# include the website portfolio link here when ready.
website_url = ""

all_dates = {}

def printIntro():
    print("\nBirthday Paradox, by Nithin Rajesh " + website_url + "\n\nThe Birthday Paradox shows us that in a group of N people, the odds that two of them have matching birthday is surprisingly large. This program does a Monte Carlo simulation (that is, repeated random simulations) to explore this concept.\n\nIt's not actually a paradox, it's just a surprising result.\n\nHow many birthdays shall I generate (Max 100):\n")

def generateRandomBirthday():
    # Generate a random birthday using the datetime module.
    # Source of Code was generated by AI in order to learn how to get the date in the form of Month and Day.
    month = random.randint(1, 12)
    year = random.randint(1900, 2100)
    max_day = (datetime.datetime(year, month + 1, 1) - datetime.timedelta(days=1)).day
    day = random.randint(1, max_day)
    date = datetime.datetime(year, month, day)
    return date.strftime("%b %d")
    

# printIntro()
# print(generateRandomBirthday())